name: securus_wallet
description: Mobile-Wallet for the crypto-currency securuscoins

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  font_awesome_flutter: ^8.5.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7


flutter:
  uses-material-design: true