name: securus_wallet
description: Mobile-Wallet for the crypto-currency securuscoins

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  font_awesome_flutter: ^8.5.0
  eva_icons_flutter:
  percent_indicator: ^2.1.1+1
  shared_preferences: ^0.5.3+4
  logger: ^0.7.0+2
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  crypto: ^2.1.3
  ffi: ^0.1.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/